# Generated by Django 3.1.8 on 2021-10-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Enter Facebook URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Enter Linkedin URL', null=True)),
                ('twitter', models.CharField(blank=True, help_text='Enter Twitter URL', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Enter Instagram username', max_length=255, null=True)),
                ('api_instagram_enabled', models.BooleanField(default=False, help_text='Enable/Disable Instagram API')),
                ('api_instagram_user_id', models.CharField(blank=True, help_text='Enter Instagram User IDL', max_length=255, null=True)),
                ('api_instagram_key', models.CharField(blank=True, help_text='Enter Instagram API key', max_length=255, null=True)),
                ('api_instagram_secret', models.CharField(blank=True, help_text='Enter Instagram API Secret', max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, help_text='Enter youtube URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=255)),
                ('about', models.TextField(blank=True, help_text='Write something about your company', max_length=1000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('nav_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, help_text='Company Address', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, help_text='ZIP', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='State', max_length=255, null=True)),
                ('email', models.EmailField(help_text='Company Official Email', max_length=255)),
                ('phone', models.CharField(help_text='Company Official Phone', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
