# Generated by Django 3.1.8 on 2021-10-07 21:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('team', wagtail.core.fields.StreamField([('teams', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.core.blocks.TextBlock(required=False)), ('title', wagtail.core.blocks.TextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True)),
                ('portfolio', wagtail.core.fields.StreamField([('portfolio', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(required=False)), ('body', wagtail.core.blocks.TextBlock(required=False)), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('thumbnail_secondary', wagtail.images.blocks.ImageChooserBlock()), ('website', wagtail.core.blocks.URLBlock(required=False)), ('linkedin', wagtail.core.blocks.URLBlock(required=False)), ('twitter', wagtail.core.blocks.URLBlock(required=False)), ('industry', wagtail.core.blocks.ChoiceBlock(choices=[('Commerce', 'Commerce'), ('Education', 'Education'), ('Health', 'Health'), ('Entertainment', 'Entertainment')], required=False))]))], blank=True, null=True)),
                ('about_us_title', models.CharField(blank=True, max_length=50, null=True)),
                ('about_us_bold', models.TextField(blank=True, max_length=1000, null=True)),
                ('about_us_small', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
