# Generated by Django 3.1.8 on 2021-10-13 18:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211012_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Industry',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='portfolio',
            field=wagtail.core.fields.StreamField([('portfolio', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(required=False)), ('body', wagtail.core.blocks.TextBlock(required=False)), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('thumbnail_secondary', wagtail.images.blocks.ImageChooserBlock()), ('website', wagtail.core.blocks.URLBlock(required=False)), ('linkedin', wagtail.core.blocks.URLBlock(required=False)), ('twitter', wagtail.core.blocks.URLBlock(required=False)), ('industry', wagtail.snippets.blocks.SnippetChooserBlock(required=True, target_model='home.industry'))]))], blank=True, null=True),
        ),
    ]
