# Generated by Django 3.1.8 on 2021-10-13 18:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211013_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='team',
            field=wagtail.core.fields.StreamField([('teams', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_secondary', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.core.blocks.TextBlock(required=False)), ('title', wagtail.core.blocks.TextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
    ]
